# Generated by Django 3.2.13 on 2022-06-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document'),
        ),
    ]
