# Generated by Django 3.2.13 on 2022-06-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_borrow_date_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='contact',
        ),
        migrations.AddField(
            model_name='reader',
            name='cellphone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cellphone number'),
        ),
        migrations.AddField(
            model_name='reader',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='landline_number_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Landline number 1'),
        ),
        migrations.AddField(
            model_name='reader',
            name='landline_number_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Landline number 2'),
        ),
    ]
