# Generated by Django 3.2.13 on 2022-06-26 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20220622_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalbook',
            name='date_register',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date Register'),
        ),
    ]
