# Generated by Django 3.2.13 on 2022-06-26 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_physicalbook_date_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='date_register',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date Register'),
        ),
    ]
