# Generated by Django 3.2.13 on 2022-06-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_reader_date_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='expected_return',
            field=models.DateField(blank=True, null=True, verbose_name='Expected return'),
        ),
    ]
